/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */

export type AlbumResponseType = (typeof AlbumResponseType)[keyof typeof AlbumResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumResponseType = {
  private: "private",
  public: "public",
} as const;
