/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */
import type { ChatControllerGetPaginationType } from "./chatControllerGetPaginationType";

export type ChatControllerGetPaginationParams = {
  page?: number;
  pageSize?: number;
  tokenAddress?: string;
  type: ChatControllerGetPaginationType;
};
