/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export type ChatControllerGetPaginationType =
  (typeof ChatControllerGetPaginationType)[keyof typeof ChatControllerGetPaginationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatControllerGetPaginationType = {
  private: "private",
  public: "public",
  global: "global",
} as const;
