/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */
import type { ChatResponseType } from "./chatResponseType";
import type { ChatResponseSenderType } from "./chatResponseSenderType";
import type { UserResponse } from "./userResponse";

export interface ChatResponse {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly type: ChatResponseType;
  readonly senderType: ChatResponseSenderType;
  readonly sender: string;
  readonly tokenAddress: string;
  readonly content: string;
  readonly image: string;
  readonly createdTime: number;
  readonly userInfo: UserResponse;
}
