/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export type ChatResponseType = (typeof ChatResponseType)[keyof typeof ChatResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatResponseType = {
  private: "private",
  public: "public",
  global: "global",
} as const;
