/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */
import type { ChatResponse } from "./chatResponse";

export interface ChatPaginationResponse {
  readonly total: number;
  readonly page: number;
  readonly pageSize: number;
  readonly data: readonly ChatResponse[];
}
