/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export type ChatResponseSenderType =
  (typeof ChatResponseSenderType)[keyof typeof ChatResponseSenderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatResponseSenderType = {
  bot: "bot",
  user: "user",
} as const;
