/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export type ClaimRequestResponseStatus =
  (typeof ClaimRequestResponseStatus)[keyof typeof ClaimRequestResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClaimRequestResponseStatus = {
  success: "success",
  pending: "pending",
  expired: "expired",
  failed: "failed",
} as const;
