/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { ClaimRequestResponseStatus } from "./claimRequestResponseStatus";

export interface ClaimRequestResponse {
  readonly amount: string;
  readonly created_at: string;
  readonly createdTime: number;
  readonly expiredTime: number;
  readonly id: string;
  readonly ownerAddress: string;
  readonly signature: string;
  readonly status: ClaimRequestResponseStatus;
  readonly updated_at: string;
}
