/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */

export interface CreateMemeOffChainResponse {
  readonly tokenAddress: string;
  readonly image: string;
  readonly description: string;
  readonly website: string;
  readonly x: string;
  readonly telegram: string;
  readonly discord: string;
  readonly github: string;
  readonly creator: string;
  readonly createdTime: number;
}
