/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export type CreateMemeOffChainDtoTypesItem =
  (typeof CreateMemeOffChainDtoTypesItem)[keyof typeof CreateMemeOffChainDtoTypesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMemeOffChainDtoTypesItem = {
  DEFAI: "DEFAI",
  Trading: "Trading",
  HedgeFund: "HedgeFund",
  Entertainment: "Entertainment",
  Meme: "Meme",
  Conversational: "Conversational",
  IP: "IP",
  BigData: "BigData",
} as const;
