/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */
import type { CreateVideoDtoPrivacy } from "./createVideoDtoPrivacy";

export interface CreateVideoDto {
  privacy?: CreateVideoDtoPrivacy;
  url: string;
  tokenAddress: string;
  tags: string[];
  caption?: string;
  allowComment?: string;
}
