/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */

export interface CreateMemeNoFeeRequestResponse {
  readonly tokenId: string;
  readonly tokenAddress: string;
  readonly signature: string;
  readonly expiredBlockNumber: string;
  readonly sender: string;
}
