/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export type CreateChatDtoType = (typeof CreateChatDtoType)[keyof typeof CreateChatDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateChatDtoType = {
  private: "private",
  public: "public",
  global: "global",
} as const;
