/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */
import type { CreateChatDtoType } from "./createChatDtoType";

export interface CreateChatDto {
  type: CreateChatDtoType;
  tokenAddress?: string;
  content?: string;
  image?: string;
}
