/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePumpeVotingDto {
  description?: string;
  logo: string;
  name: string;
  owner: string;
  symbol: string;
  telegram?: string;
  website?: string;
  x?: string;
}
