/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */
import type { MiniAppWalletAuthSuccessPayload } from "./miniAppWalletAuthSuccessPayload";

export interface LoginDto {
  payload: MiniAppWalletAuthSuccessPayload;
  nonce: string;
  username: string;
}
