/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export type MemeResponseAndPriceStatus =
  (typeof MemeResponseAndPriceStatus)[keyof typeof MemeResponseAndPriceStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemeResponseAndPriceStatus = {
  active: "active",
  hidden: "hidden",
  ended: "ended",
  completed: "completed",
} as const;
