/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */

export type MemeControllerQueryPaginationTypesItem =
  (typeof MemeControllerQueryPaginationTypesItem)[keyof typeof MemeControllerQueryPaginationTypesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemeControllerQueryPaginationTypesItem = {
  DEFAI: "DEFAI",
  Trading: "Trading",
  HedgeFund: "HedgeFund",
  Entertainment: "Entertainment",
  Meme: "Meme",
  Conversational: "Conversational",
  IP: "IP",
  BigData: "BigData",
} as const;
