/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */
import type { MemeControllerQueryPaginationSortBy } from "./memeControllerQueryPaginationSortBy";
import type { MemeControllerQueryPaginationSortOrder } from "./memeControllerQueryPaginationSortOrder";
import type { MemeControllerQueryPaginationFilter } from "./memeControllerQueryPaginationFilter";

export type MemeControllerQueryPaginationParams = {
  page?: number;
  pageSize?: number;
  search?: string;
  sortBy?: MemeControllerQueryPaginationSortBy;
  sortOrder?: MemeControllerQueryPaginationSortOrder;
  filter?: MemeControllerQueryPaginationFilter;
  creator?: string;
  holder?: string;
  createdTime?: number;
};
