/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */
import type { MemeResponseAndPriceStatus } from "./memeResponseAndPriceStatus";

export interface MemeResponseAndPrice {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly status: MemeResponseAndPriceStatus;
  readonly nativeAddress: string;
  readonly nativeName: string;
  readonly nativeSymbol: string;
  readonly nativeDecimals: string;
  readonly nativeImage: string;
  readonly whiteListStartTime: number;
  readonly whiteListEndTime: number;
  readonly factory: string;
  readonly tokenAddress: string;
  readonly pumpAddress: string;
  readonly creator: string;
  readonly name: string;
  readonly symbol: string;
  readonly decimals: string;
  readonly image: string;
  readonly offChainImage: string;
  readonly description: string;
  readonly agentBio: readonly string[];
  readonly x: string;
  readonly telegram: string;
  readonly discord: string;
  readonly website: string;
  readonly tokenOffset: string;
  readonly nativeOffset: string;
  readonly totalSupply: string;
  readonly saleAmount: string;
  readonly reservedSupply: string;
  readonly virtualNativeReserve: string;
  readonly virtualTokenReserve: string;
  readonly createdTime: number;
  readonly graduatedTime: number;
  readonly volume24hs: string;
  readonly marketCap: string;
  readonly numOfHolders: number;
  readonly dexScreenerPairUrl: string;
  readonly dexToolsPairUrl: string;
  readonly listProgress: string;
  readonly price24hChange: string;
}
