/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export interface OHLCItem {
  readonly time: number;
  readonly o: string;
  readonly h: string;
  readonly l: string;
  readonly c: string;
}
