/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export type OhlcControllerFindResolution =
  (typeof OhlcControllerFindResolution)[keyof typeof OhlcControllerFindResolution];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OhlcControllerFindResolution = {
  NUMBER_60: "60",
  NUMBER_300: "300",
  NUMBER_3600: "3600",
  NUMBER_86400: "86400",
} as const;
