/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export type PumpeControllerFindPaginationSortOrder =
  (typeof PumpeControllerFindPaginationSortOrder)[keyof typeof PumpeControllerFindPaginationSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PumpeControllerFindPaginationSortOrder = {
  DESC: "DESC",
  ASC: "ASC",
} as const;
