/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { CommentResponse } from "./commentResponse";

export interface PumpeComments {
  readonly comments: readonly CommentResponse[];
  readonly total: number;
}
