/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { PumpeAndPriceResponse } from "./pumpeAndPriceResponse";

export interface PumpeResponseList {
  readonly data: readonly PumpeAndPriceResponse[];
  readonly page: number;
  readonly pageSize: number;
  readonly total: number;
}
