/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export type PumpeControllerFindPaginationFilter =
  (typeof PumpeControllerFindPaginationFilter)[keyof typeof PumpeControllerFindPaginationFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PumpeControllerFindPaginationFilter = {
  all: "all",
  end: "end",
  launching: "launching",
} as const;
