/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { PumpeControllerFindPaginationSortBy } from "./pumpeControllerFindPaginationSortBy";
import type { PumpeControllerFindPaginationStatus } from "./pumpeControllerFindPaginationStatus";
import type { PumpeControllerFindPaginationSortOrder } from "./pumpeControllerFindPaginationSortOrder";
import type { PumpeControllerFindPaginationFilter } from "./pumpeControllerFindPaginationFilter";

export type PumpeControllerFindPaginationParams = {
  page?: number;
  pageSize?: number;
  search?: string;
  sortBy?: PumpeControllerFindPaginationSortBy;
  status?: PumpeControllerFindPaginationStatus;
  sortOrder?: PumpeControllerFindPaginationSortOrder;
  filter?: PumpeControllerFindPaginationFilter;
};
