/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { ReferralItem } from "./referralItem";

export interface ReferralResponse {
  readonly referral: readonly ReferralItem[];
  readonly total: string;
}
