/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */

export type ResponseClaimParamDtoClaimState =
  (typeof ResponseClaimParamDtoClaimState)[keyof typeof ResponseClaimParamDtoClaimState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseClaimParamDtoClaimState = {
  active: "active",
  completed: "completed",
  ineligible: "ineligible",
} as const;
