/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */
import type { ResponseClaimParamDtoClaimState } from "./responseClaimParamDtoClaimState";

export interface ResponseClaimParamDto {
  readonly id: string;
  readonly chainId: string;
  readonly tokenAddress: string;
  readonly amount: string;
  readonly payload: string;
  readonly expiredBlockNumber: string;
  readonly signature: string;
  readonly adminAddress: string;
  readonly recipient: string;
  readonly claimState: ResponseClaimParamDtoClaimState;
  readonly claimNonce: string;
}
