/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { TokenLockResponse } from "./tokenLockResponse";

export interface TokenLockPaginationResponse {
  readonly data: readonly TokenLockResponse[];
  readonly page: number;
  readonly pageSize: number;
  readonly total: number;
}
