/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export type TokenLockControllerFindPaginationSortOrder =
  (typeof TokenLockControllerFindPaginationSortOrder)[keyof typeof TokenLockControllerFindPaginationSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenLockControllerFindPaginationSortOrder = {
  DESC: "DESC",
  ASC: "ASC",
} as const;
