/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export type TokenLockControllerFindPaginationFilter =
  (typeof TokenLockControllerFindPaginationFilter)[keyof typeof TokenLockControllerFindPaginationFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenLockControllerFindPaginationFilter = {
  all: "all",
  end: "end",
  launching: "launching",
} as const;
