/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export type TokenLockResponseStatus =
  (typeof TokenLockResponseStatus)[keyof typeof TokenLockResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenLockResponseStatus = {
  hidden: "hidden",
  normal: "normal",
  completed: "completed",
  vesting: "vesting",
} as const;
