/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { TokenLockResponseStatus } from "./tokenLockResponseStatus";
import type { TokenResponse } from "./tokenResponse";

export interface TokenLockResponse {
  readonly address: string;
  readonly amountCanClaim: string;
  readonly claimedAmount: string;
  readonly claimer: string;
  readonly created_at: string;
  readonly createdTime: number;
  readonly id: number;
  readonly interval: string;
  readonly lockAmount: string;
  readonly lockFactory: string;
  readonly nextVestingTime: number;
  readonly releaseAmountAtTge: string;
  readonly releaseAmountCycle: string;
  readonly status: TokenLockResponseStatus;
  readonly tge: string;
  readonly title: string;
  readonly token: TokenResponse;
  readonly tokenAddress: string;
  readonly updated_at: string;
}
