/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export interface TokenResponse {
  readonly address: string;
  readonly decimals: string;
  readonly name: string;
  readonly symbol: string;
  readonly totalSupply: string;
}
