/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { TokenLockControllerFindPaginationSortBy } from "./tokenLockControllerFindPaginationSortBy";
import type { TokenLockControllerFindPaginationSortOrder } from "./tokenLockControllerFindPaginationSortOrder";
import type { TokenLockControllerFindPaginationFilter } from "./tokenLockControllerFindPaginationFilter";

export type TokenLockControllerFindPaginationParams = {
  page?: number;
  pageSize?: number;
  sortBy?: TokenLockControllerFindPaginationSortBy;
  sortOrder?: TokenLockControllerFindPaginationSortOrder;
  filter?: TokenLockControllerFindPaginationFilter;
  search?: string;
  claimer?: string;
};
