/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export type TokenLockControllerFindPaginationSortBy =
  (typeof TokenLockControllerFindPaginationSortBy)[keyof typeof TokenLockControllerFindPaginationSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenLockControllerFindPaginationSortBy = {
  createdTime: "createdTime",
  claimedAmount: "claimedAmount",
} as const;
