/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */
import type { TransactionHighlightResponseType } from "./transactionHighlightResponseType";
import type { UserResponse } from "./userResponse";
import type { MemeResponse } from "./memeResponse";

export interface TransactionHighlightResponse {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly type: TransactionHighlightResponseType;
  readonly creator: string;
  readonly tokenAddress: string;
  readonly tx: string;
  readonly createdTime: number;
  readonly amountToken: string;
  readonly amountNative: string;
  readonly volume: string;
  readonly virtualTokenReserve: string;
  readonly virtualNativeReserve: string;
  readonly userInfo: UserResponse;
  readonly tokenInfo: MemeResponse;
}
