/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */

export type TransactionResponseType =
  (typeof TransactionResponseType)[keyof typeof TransactionResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionResponseType = {
  PumpTokenCreated: "PumpTokenCreated",
  Buy: "Buy",
  Sell: "Sell",
  Pump: "Pump",
  TotalPumpedChanged: "TotalPumpedChanged",
  List: "List",
} as const;
