/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PUMPE MEME API
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionResponseMetaData } from "./transactionResponseMetaData";
import type { PumpeBaseResponse } from "./pumpeBaseResponse";
import type { TransactionResponseType } from "./transactionResponseType";

export interface TransactionResponse {
  readonly amountIn: string;
  readonly amountOut: string;
  readonly bought: string;
  readonly created_at: string;
  readonly createdTime: number;
  readonly id: number;
  readonly metaData: TransactionResponseMetaData;
  readonly pumpe: PumpeBaseResponse;
  readonly pumpeAddress: string;
  readonly recipient: string;
  readonly reserveToBuy: string;
  readonly transaction: string;
  readonly type: TransactionResponseType;
  readonly updated_at: string;
  readonly volume: number;
}
