/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Slide World API
 * OpenAPI spec version: 0.0.12
 */

export type TransactionHighlightResponseType =
  (typeof TransactionHighlightResponseType)[keyof typeof TransactionHighlightResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionHighlightResponseType = {
  MemeCreated: "MemeCreated",
  Buy: "Buy",
  Sell: "Sell",
  List: "List",
  BondingCurveEnded: "BondingCurveEnded",
} as const;
