/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */
import type { UserControllerFindFollowersPaginationSortBy } from "./userControllerFindFollowersPaginationSortBy";
import type { UserControllerFindFollowersPaginationSortOrder } from "./userControllerFindFollowersPaginationSortOrder";

export type UserControllerFindFollowersPaginationParams = {
  page?: number;
  pageSize?: number;
  sortBy?: UserControllerFindFollowersPaginationSortBy;
  sortOrder?: UserControllerFindFollowersPaginationSortOrder;
  search?: string;
  userWalletAddress: string;
};
