/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */

export type UserControllerFindFollowingPaginationSortBy =
  (typeof UserControllerFindFollowingPaginationSortBy)[keyof typeof UserControllerFindFollowingPaginationSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserControllerFindFollowingPaginationSortBy = {
  createdTime: "createdTime",
} as const;
