/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */
import type { UserControllerFindFollowingPaginationSortBy } from "./userControllerFindFollowingPaginationSortBy";
import type { UserControllerFindFollowingPaginationSortOrder } from "./userControllerFindFollowingPaginationSortOrder";

export type UserControllerFindFollowingPaginationParams = {
  page?: number;
  pageSize?: number;
  sortBy?: UserControllerFindFollowingPaginationSortBy;
  sortOrder?: UserControllerFindFollowingPaginationSortOrder;
  search?: string;
  userWalletAddress: string;
};
