/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */

export type UserControllerFindFollowingPaginationSortOrder =
  (typeof UserControllerFindFollowingPaginationSortOrder)[keyof typeof UserControllerFindFollowingPaginationSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserControllerFindFollowingPaginationSortOrder = {
  DESC: "DESC",
  ASC: "ASC",
} as const;
