/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */
import type { VerifyHumanSuccessResult } from "./verifyHumanSuccessResult";

export interface VerifyHumanDto {
  action: string;
  signal: string;
  payload: VerifyHumanSuccessResult;
}
