/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */

export type VideoResponsePrivacy = (typeof VideoResponsePrivacy)[keyof typeof VideoResponsePrivacy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VideoResponsePrivacy = {
  public: "public",
  private: "private",
  friends: "friends",
  followers: "followers",
  hidden: "hidden",
} as const;
