/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swipe Pad API
 * OpenAPI spec version: 0.0.12
 */
import type { VideoResponsePrivacy } from "./videoResponsePrivacy";
import type { MemeResponse } from "./memeResponse";

export interface VideoResponse {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly privacy: VideoResponsePrivacy;
  readonly url: string;
  readonly tokenAddress: string;
  readonly creatorAddress: string;
  readonly tags: readonly string[];
  readonly caption: string;
  readonly allowComment: boolean;
  readonly totalLike: number;
  readonly totalComments: number;
  readonly createdTime: number;
  readonly isUserLike: boolean;
  readonly memeInfo: MemeResponse;
}
